name: ⭐️ Feature Request
description: Suggest a new feature or improvement for the GitHub Copilot CLI.
type: Feature
labels:
  - enhancement
  - "needs triage"
body:
  - type: markdown
    attributes:
      value: |
        <br />
        Thank you for taking the time to suggest a feature! Please answer each question below to the best of your ability; it is okay to leave questions blank if you have to.
  - type: input
    id: title
    attributes:
      label: Describe the feature or problem you'd like to solve
      description: A clear and concise description of what the feature or porblem is.
  - type: textarea
    id: description
    attributes:
      label: Proposed solution
      description: How will it benefit GitHub Copilot CLI and its users?
  - type: textarea
    id: examples
    attributes:
      label: Example prompts or workflows
      description: Share 3-5 example prompts or workflows it would enabled; just enough detail to show value.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
      placeholder: |
        - Screenshots or mockups
