name: Close issue/PR on adding invalid label

# **What it does**: This action closes issues that are labeled as invalid in the repo.

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  close-on-adding-invalid-label:
    if:
      github.repository == 'github/copilot-cli' && github.event.label.name ==
      'invalid'
    runs-on: ubuntu-latest

    steps:
      - name: Close issue
        if: ${{ github.event_name == 'issues' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.issue.html_url }}
        run: gh issue close $URL

      - name: Close PR
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr close $URL
