name: Add enhancement comment
on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  add-comment-to-enhancement-issues:
    if: github.event.label.name == 'enhancement'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.issue.number }}
      BODY: >
        Thank you for your issue! We have categorized it as an enhancement,
        and it has been added to our backlog. In doing so, **we are not
        committing to implementing this feature at this time**, but, we will
        consider it for future releases based on community feedback and our own
        product roadmap. 


        **If you come across this issue and would like to see it implemented,
        please add a thumbs up!** This will help us prioritize the feature.
        Please only comment if you have additional information or viewpoints to
        contribute.
    steps:
      - run: gh issue comment "$NUMBER" --body "$BODY"
